services:
  - type: web
    name: CV-MAKER
    runtime: node
    region: tokyo
    buildCommand: cd backend && npm install && cd ../frontend && npm install && npm run build && cd ../backend
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: SQLD_URL
        value: libsql://cv-maker-voicenotesite.aws-ap-northeast-1.turso.io
      - key: TURSO_AUTH_TOKEN
        sync: false
